// <auto-generated />
namespace DigitaalOmgevingsboek.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatedLog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedLog));
        
        string IMigrationMetadata.Id
        {
            get { return "201506150931255_updated Log"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
